apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  strategy: {}
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: javatest
            - name: MYSQL_PASSWORD
              value: nkUKXaBY{Yws
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: example_db_user
          image: sergeytim/task:mysql
          name: db
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
