apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.db.name }}
  strategy: {}
  template:
    metadata:
      labels:
        service: {{ .Values.db.name }}
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: javatest
            - name: MYSQL_PASSWORD
              value: nkUKXaBY{Yws
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: example_db_user
          image: {{ .Values.db.image }}
          name: {{ .Values.db.name }}
          ports:
            - containerPort: {{ .Values.db.port }}
          resources: {}
      restartPolicy: Always
status: {}
