apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.db.name }}
  name: {{ .Values.db.name }}
spec:
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    service: {{ .Values.db.name }}
status:
  loadBalancer: {}
