apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.nginx.service.name }}
  name: {{ .Values.nginx.service.name }}
spec:
  ports:
    - port: {{ .Values.nginx.service.port }}
      name: {{ .Values.nginx.containers.port }}
      targetPort: {{ .Values.nginx.service.port }}
    - port: {{ .Values.nginx.service.targetPort }}
      name: {{ .Values.tomcat.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
  selector:
    service: {{ .Values.nginx.name }}
status:
  loadBalancer: {}
